### ISSUE TITLE
chemlab view

### ISSUE THREAD

**Issue by exit-1** [chemlab/chemlab#127]
When following the [Molecular Viewer guide](http://chemlab.readthedocs.org/en/latest/mviewer.html#changing-the-appeareance) and running `chemlab view`, I get an error for too few arguments rather than the user interface and the IPython Shell. Error below. 

```
$ chemlab view

usage: chemlab view [-h] [--traj TRAJ] [--nowater] [--smooth] [--skip SKIP]
                    [--translate TRANSLATE]
                    filename
chemlab view: error: too few arguments
```

Also, `chemlab view` cannot open xyz files.

I installed chemlab using 
`pip install git+git://github.com/chemlab/chemlab.git`

**Comment by gabrielelanaro** [comment]
That's an easy fix I'll work on it during this week, I was in vacation till now.

**Comment by gabrielelanaro** [comment]
I tried to apply some fixes now? I also suspect that the chemlab command you're running refers to an older version, so try to clean it up before reinstalling (like with pip uninstall).

I'm also having a lot of issues with PyQt right now, so I'm focusing my development efforts on the WebGL backend (gabrielelanaro/chemview), so that we integrate easily with IPython notebook

**Comment by exit-1** [comment]
Thanks for the update. I believe in your last update, you started using python package SIP, and not added it to requirements.txt, so I get this error:


    Traceback (most recent call last):
      File "/home/ben/opt/apps/anaconda/bin/chemlab", line 4, in <module>
        import chemlab as cl
       File "/home/ben/opt/apps/anaconda/lib/python2.7/site-packages/chemlab/__init__.py", line 4, in  <module>
        import sip
        ImportError: No module named sip


I am trying to get SIP now, but it is not available on pip from what I have seen, and the [package wiki](https://wiki.python.org/moin/SIP) seems to be outdated and full of dead links. I'll try to find a download and build it from source, then try again, unless you have another recommendation.

**Comment by gabrielelanaro** [comment]
Yes, sip is actually a dependency of pyqt4. If you're using anaconda I
believe the command is conda install pyqt.

What is happening is that the embedded IPython console component runs on
PyQt and for this reason I had to switch from PySide to PyQt (plus some
config hacks).

Thanks for the update. I believe in your last update, you started using
python package SIP, and not added it to requirements.txt, so I get this
error:

Traceback (most recent call last):
  File "/home/ben/opt/apps/anaconda/bin/chemlab", line 4, in <module>
    import chemlab as cl
   File "/home/ben/opt/apps/anaconda/lib/python2.7/site-packages/chemlab/__init__.py",
line 4, in  <module>
    import sip
    ImportError: No module named sip

I am trying to get SIP now, but it is not available on pip from what I have
seen, and the package wiki <https://wiki.python.org/moin/SIP> seems to be
outdated and full of dead links. I'll try to find a download and build it
from source, then try again, unless you have another recommendation.

—
Reply to this email directly or view it on GitHub
<https://github.com/chemlab/chemlab/issues/127#issuecomment-68795980>.

**Comment by exit-1** [comment]
Ah, I see. I recently got off the anaconda bandwagon. PyQt4 and SIP are quite annoying to install without it. See [here](http://movingthelamppost.com/blog/html/2013/07/12/installing_pyqt____because_it_s_too_good_for_pip_or_easy_install_.html).

Is it planned to eventually merge chemview into chemlab as the IPython submodule? Do you plan on sticking with PyQt4?

**Comment by gabrielelanaro** [comment]
I think chemview is going to be a separate project but with tight integration (used as a backend). I'm not sure if it makes sense to maintain also the PyQt/PySide backend in parallel, mainly because of the many compatibility issues that affect both PyQt and OpenGL implementations. Therefore right now I'm leaning towards dropping the chemlab.graphics part in favor of chemview and the notebook API.
