### ISSUE TITLE
QtViewer Failure

### ISSUE THREAD

**Issue by oscarbranson** [chemlab/chemlab#130]
**QtViewer throws RuntimeError.**
- Mac OS X (10.10.3)
- Clean Anaconda install (at posting date).
- chemlab 0.4, installed by: conda install chemlab

Initially, QtViewer would not import:

    from chemlab.graphics import QtViewer
    
    > No package named ImageFont

Fixed by:

    conda install pil

After fix, running the minimal 'Graphics and Visualisation' example [here](http://chemlab.readthedocs.org/en/latest/graphics.html) throws a RuntimeError:

    from chemlab.graphics import QtViewer
    v = QtViewer()
    
    from chemlab.graphics.renderers import AtomRenderer
    from chemlab.db  import ChemlabDB
    water = ChemlabDB().get('molecule', 'example.water')
    ar = v.add_renderer(AtomRenderer, water.r_array, water.type_array)
    v.run()

    > ---------------------------------------------------------------------------
    > RuntimeError                              Traceback (most recent call last)
    > <ipython-input-4-6f03517c4aaa> in <module>()
    >       5 from chemlab.db  import ChemlabDB
    >       6 water = ChemlabDB().get('molecule', 'example.water')
    > ----> 7 ar = v.add_renderer(AtomRenderer, water.r_array, water.type_array)
    >       8 v.run()
    > 
    > /Users/***/anaconda/lib/python2.7/site-packages/chemlab/graphics/qtviewer.pyc in add_renderer(self,     klass, *args, **kwargs)
    >     149 
    >     150         '''
    > --> 151         renderer = klass(self.widget, *args, **kwargs)
    >     152         self.widget.renderers.append(renderer)
    >     153         return renderer
    > 
    > /Users/***/anaconda/lib/python2.7/site-packages/chemlab/graphics/renderers/atom.pyc in __init__(self,     widget, r_array, type_array, backend, color_scheme, radii_map, shading)
    >      62         elif backend == 'impostors':
    >      63             self.sr = SphereImpostorRenderer(widget, r_array, radii,
    > ---> 64                                              colorlist, shading=shading)
    >      65         elif backend == 'points':
    >      66             self.sr = PointRenderer(widget, r_array, colorlist)
    > 
    > /Users/***/anaconda/lib/python2.7/site-packages/chemlab/graphics/renderers/sphere_imp.pyc in __init__(    self, viewer, poslist, radiuslist, colorlist, transparent, shading)
    >      31                                                 "sphereimp.frag")
    >      32 
    > ---> 33         super(SphereImpostorRenderer, self).__init__(viewer, vert, frag)
    >      34 
    >      35         self.transparent = transparent
    > 
    > /Users/***/anaconda/lib/python2.7/site-packages/chemlab/graphics/renderers/base.pyc in __init__(self,     widget, vertex, fragment)
    >      69         self.VERTEX_SHADER = vertex
    >      70         self.FRAGMENT_SHADER = fragment
    > ---> 71         self.compile_shader()
    >      72 
    >      73     def draw(self):
    > 
    > /Users/***/anaconda/lib/python2.7/site-packages/chemlab/graphics/renderers/base.pyc in compile_shader(    self)
    >      88                                  GL_FRAGMENT_SHADER)
    >      89 
    > ---> 90         self.shader = shaders.compileProgram(vertex, fragment)
    >      91 
    >      92     def setup_shader(self):
    > 
    > /Users/***/anaconda/lib/python2.7/site-packages/OpenGL/GL/shaders.pyc in compileProgram(*shaders,     **named)
    >     204     glLinkProgram(program)
    >     205     if named.get('validate', True):
    > --> 206         program.check_validate()
    >     207     program.check_linked()
    >     208     for shader in shaders:
    > 
    > /Users/***/anaconda/lib/python2.7/site-packages/OpenGL/GL/shaders.pyc in check_validate(self)
    >     107                 """Validation failure (%r): %s"""%(
    >     108                 validation,
    > --> 109                 glGetProgramInfoLog( self ),
    >     110             ))
    >     111         self.validated = True
    > 
    > RuntimeError: Validation failure (0): Validation Failed: Current draw framebuffer is invalid.

**Comment by gabrielelanaro** [comment]
For the pil I'll add the dependency. About the framebuffer error, even if I can't reproduce on my machine I have an idea on what it might be. It's a bug due to Qt that affects some drivers. Can you try to add a ``show`` call before calling add_renderer? That may solve the problem. (we basically need to create a display, or framebuffer, before initializing the renderers, and we may do that with show). Otherwise I'll have an access to a Mac next week and fix it myself.

    from chemlab.graphics import QtViewer
    v = QtViewer()
    v.show() # Here
    from chemlab.graphics.renderers import AtomRenderer
    from chemlab.db  import ChemlabDB
    water = ChemlabDB().get('molecule', 'example.water')
    ar = v.add_renderer(AtomRenderer, water.r_array, water.type_array)
    v.run()
