### ISSUE TITLE
QtViewer: objects 'bleed' through the opposite side if out-of-window

### ISSUE THREAD

**Issue by jaimergp** [chemlab/chemlab#132]
It's like part of the bottom of  the window is 'bleeding' at the upper part. Screenshots attached.

Everything is fine if the molecule is within the window.
![ok](https://cloud.githubusercontent.com/assets/2559438/8034821/bbd1cdce-0deb-11e5-9dd9-8c80343f9f3e.png)

But as soon as part of the object leaves the window, it bleeds through the opposite side.
![notok](https://cloud.githubusercontent.com/assets/2559438/8034822/bbd38eb6-0deb-11e5-853e-ff04af231a85.png)

**Comment by gabrielelanaro** [comment]
Thanks, I didn't notice that. I've started to work on this issue, it's a problem of the outline effect, I'm narrowing down the issue but being shader code it's a bit tricky
