### ISSUE TITLE
Dynamically adjusted OutlineEffect line width, and coloring

### ISSUE THREAD

**Issue by jaimergp** [chemlab/chemlab#136]
Hi again!

I really like the postprocessing capabilities of chemlab viewer! They are easy to apply and perform really well. However, I would like to discuss something about OutlineEffect.

When the camera is close to the molecule, the outline is perfect: smooth and uniform, with the proper width.

![close](https://cloud.githubusercontent.com/assets/2559438/9900740/09148e4e-5c63-11e5-802b-1a517957aafc.png)

However, if the camera zooms out, the outline effect keeps the original width and, being that far, the rendering loses part of its beauty:

![far](https://cloud.githubusercontent.com/assets/2559438/9900742/0b396e42-5c63-11e5-9ad6-b79a721625cd.png)

My question is: can the outline width be adjusted to the camera distance? Also, is it possible to change the color of the outline? 

Thank you very much!

**Comment by gabrielelanaro** [comment]
Hi, the outline thickness is a bit tricky to change due to how the outline-detection works. 

Color should be possible, I'm going to try it to implement it tomorrow

**Comment by gabrielelanaro** [comment]
The coloring is implemented in latest master: to add a blue outline:
```
v.add_post_processing(OutlineEffect, 'depthnormal', color=[0, 0, 1])
```

**Comment by jaimergp** [comment]
As a workaround, would it be possible to disable the OutlineEffect (and potentially, other postprocessing effects) when the camera distance value is big enough? Do we have any triggers or signals to monitor that?

**Comment by gabrielelanaro** [comment]
This is possible. Right not I'm making the cartoon/ribbon renderer so I can't fix that right away. 

As an immediate workaround you could connect to the qt mouse/keyboard events and check the distance from the camera (through the attribute camera of the molecular viewer) and remove/add the postprocessing effect. 

To calculate the distance from the central point (pivot) and the camera:
https://github.com/chemlab/chemlab/blob/681b55faaec6d1e7097b6715ebb34d7bd1f95386/chemlab/graphics/camera.py#L165
