### ISSUE TITLE
In installation add PyPI and pip 

### ISSUE THREAD

**Issue by salotz** [chemlab/chemlab#142]
I think you should add an entry in the install docs for the PyPI repository and pip. That was the easiest for me if you don't use anaconda or want to do it from source.

**Comment by hainm** [comment]
looking at the dependencies I don't think it's easy to install `chemlab` via pip.

```bash
sudo apt-get install python-numpy python-scipy python-opengl cython 
python-matplotlib python-qt4-gl python-qt4
```

I myself prefer install from conda.

(any way, this depend on personal taste).

**Comment by salotz** [comment]
I got it up and running just with pip but I've since seen the light of anaconda, however it doesn't seem to work for me. It doesn't even come up on a `conda search chemlab`.

**Comment by gabrielelanaro** [comment]
I'm glad this is working with pip, anaconda comes with pyqt and the other dependencies.

chemlab (from git) is currently being tested for Python 2.7 and 3.5 using the following command line:

https://travis-ci.org/chemlab/chemlab/jobs/108104817
