### ISSUE TITLE
The conda installer

### ISSUE THREAD

**Issue by salotz** [chemlab/chemlab#148]
Hello,
The conda installer doesn't seem to be working. For me at least conda can't find chemlab. I tried both the new channel "https://conda.anaconda.org/gabrielelanaro" and the one still on the documentation  "http://conda.binstar.org/gabrielelanaro".

Hope this can be fixed as I am having trouble with Qt dependencies I think when I manually install it.

Love the package! I hate using vmd and do I really want this style molecule viewer to work out. Would like to become a contributor, at least on the protein support side of things.

~Sam

**Comment by hainm** [comment]
works for me, just tried

```bash
$ conda install chemlab -c https://conda.anaconda.org/gabrielelanaro
Fetching package metadata: ......
Solving package specifications: ..........................................
Package plan for installation in environment /project1/dacase-001/haichit/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    freeglut-2.8.1             |                0         540 KB
    libpng-1.6.17              |                0         214 KB
    libsodium-1.0.3            |                0         774 KB
    freetype-2.5.5             |                0         2.2 MB

.... (cut)
```

>  I hate using vmd

well, vmd has been developed for many year with strong funding. It's good for what it is supposed to.

**Comment by gabrielelanaro** [comment]
@salotz are you on windows? I think you can't find chemlab because it isn't compiled for windows in the conda channel (linux and mac versions are available).

I'm in the process of making a new (big) release, which is much better than the previous version, and I'll package that for windows as well.

Besides, I'm kinda neglecting the qt backend in favor of the notebook backend (through chemview), simply because the qt backend relies opengl which is a nightmare to deal with (each driver has his own implementation, and his own bugs that unfortunately I can't fix...).

**Comment by salotz** [comment]
No, I'm on Ubuntu 14.04 and it's because I was using python 3. I get:

```
Fetching package metadata: ......
Solving package specifications: ................
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ]|###################| 100%


Hint: the following packages conflict with each other:
  - chemlab
  - python 3.5*
```
I switched to a python 2 env and it worked.  But if I installed chemlab from source I could get it to work with python3 and same software installed.

I agree about vmd being a good program overall, I'm just excited for this project so I don't have as much context switching. Plus I find using vmd to be a bit clumsy.

The notebooks are kind of cool but to be honest I would rather be using the OpenGL frames and interact with it through a terminal. I suppose if you can get the notebooks to have the same general functionality that would be good, but having the extra layer of the notebook and being forced to use that editor is a bit of a drag perhaps. I'll continue testing it out and give you my feedback though!

**Comment by hainm** [comment]
> Besides, I'm kinda neglecting the qt backend in favor of the notebook backend (through chemview), simply because the qt backend relies opengl which is a nightmare to deal with (each driver has his own implementation, and his own bugs that unfortunately I can't fix...).

:+1:
